apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: spiffe-demo-base

resources:
  - namespace.yaml
  - opa-policies-configmap.yaml
  - services.yaml
  - deployments.yaml
  - keycloak.yaml

configMapGenerator:
    - name: keycloak-realm
      namespace: spiffe-demo
      files:
        - realm-spiffe-demo.json=../../keycloak/realm-spiffe-demo.json
      options:
        disableNameSuffixHash: true