apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jaeger
  namespace: spiffe-demo
spec:
  to:
    kind: Service
    name: jaeger
    weight: 100
  port:
    targetPort: 16686
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
