# AuthProxy configuration for token exchange
apiVersion: v1
kind: Secret
metadata:
  name: authbridge-proxy-config
  namespace: spiffe-demo
type: Opaque
stringData:
  TOKEN_URL: "http://keycloak:8080/realms/spiffe-demo/protocol/openid-connect/token"
  ISSUER: "http://keycloak.localtest.me:8080/realms/spiffe-demo"
  TARGET_AUDIENCE: "document-service"
  TARGET_SCOPES: "openid document-service-aud"
